# Generated by Django 6.0.1 on 2026-01-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='baker',
        ),
        migrations.DeleteModel(
            name='Baker',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
